# Pipline
> Token IDs → Embedding layer → 1D convolution → ReLU → Masked global max pooling → Dropout  → Fully connected classification layer → Binary prediction

Can pre-learning semantic and sentiment information improve IMDb sentiment classification performance?

Do 50k unlabeled movie reviews offer any additional value?

# Work

## Embedding

[1]. Maas, A. L., Daly, R. E., Pham, P. T., Huang, D., Ng, A. Y., & Potts, C. (2011). Learning word vectors
for sentiment analysis. Proceedings of the 49th Annual Meeting of the Association for Computational Linguistics: Human
Language Technologies, 142–150. https://ai.stanford.edu/~ang/papers/acl11-WordVectorsSentimentAnalysis.pdf

In [ ]:
#Hyperparameters

# Data
DATASET_NAME = "Kwaai/IMDB_Sentiment"
VALID_RATIO = 0.20

# Vocabulary
VOCAB_SIZE = 8_000
DROP_TOP_N = 50
PROTECTED_TOKENS = {
    "not", "no", "never", "neither", "nor",
    "but", "however", "although", "though", "yet",
    "good", "bad", "great", "best", "worst",
    "like", "love", "hate", "enjoy",
    "very", "really", "too", "so", "just",
    "more", "most", "less", "least",
    "hardly", "barely", "scarcely",
}
# Embedding model
EMBED_DIM = 50
EMBED_INIT_STD = 0.02

# Optimisation
MAX_EPOCHS = 30
EARLY_STOPPING_PATIENCE = 4
EARLY_STOPPING_MIN_DELTA = 1e-3
BATCH_SIZE = 256
LEARNING_RATE = 2e-3
WEIGHT_DECAY = 1e-5
SENTIMENT_WEIGHT = 1.0
GRAD_CLIP = 5.0

# Reproducibility and output
SEED = 42
DEVICE = "auto"
NUM_WORKERS=8

In [ ]:
#import
import html
import random
import re
from collections import Counter
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from datasets import load_dataset
from torch.utils.data import DataLoader, TensorDataset
from tqdm.auto import tqdm


def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def resolve_device(name):
    if name != "auto":
        return torch.device(name)
    if torch.cuda.is_available():
        return torch.device("cuda")
    if hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


set_seed(SEED)
device = resolve_device(DEVICE)

print("Device:", device)

c:\Users\lulu\anaconda3\envs\yolo\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Device: cuda

In [ ]:
#get_data
raw_dataset = load_dataset(
    DATASET_NAME,
    download_mode="force_redownload",
)

labelled_split = raw_dataset["train"].train_test_split(
    test_size=VALID_RATIO,
    seed=SEED,
    stratify_by_column="label",
)

train_dataset = labelled_split["train"]
valid_dataset = labelled_split["test"]
unlabelled_dataset = raw_dataset["unsupervised"]
test_dataset = raw_dataset["test"]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Generating train split: 100%|██████████| 25000/25000 [00:00<00:00, 373141.46 examples/s]
Generating test split: 100%|██████████| 25000/25000 [00:00<00:00, 416668.72 examples/s]
Generating unsupervised split: 100%|██████████| 50000/50000 [00:00<00:00, 531921.07 examples/s]

In [ ]:
train_dataset.to_pandas()["label"].value_counts()

label
1    10000
0    10000
Name: count, dtype: int64

In [ ]:
valid_dataset.to_pandas()["label"].value_counts()

label
0    2500
1    2500
Name: count, dtype: int64

In [ ]:
test_dataset.to_pandas()["label"].value_counts()

label
0    12500
1    12500
Name: count, dtype: int64

word bank

In [ ]:
BREAK_PATTERN = re.compile(r"<br\s*/?>", flags=re.IGNORECASE)
TOKEN_PATTERN = re.compile(
    r"[a-z]+(?:'[a-z]+)?|[!?]+|[:;=8xX][\-^']?[)(/\\dDpP]"
)


def tokenise(text):
    text = html.unescape(text)
    text = BREAK_PATTERN.sub(" ", text)
    return TOKEN_PATTERN.findall(text.lower())

In [ ]:
token_counts = Counter()

for text in tqdm(
    train_dataset["text"],
    desc=f"Building vocabulary from {len(train_dataset):,} train reviews",
):
    token_counts.update(tokenise(text))

ranked_tokens = token_counts.most_common()


def is_protected_token(token):
    return (
        token in PROTECTED_TOKENS
        or token.endswith("n't")
        or re.fullmatch(r"[!?]+", token) is not None
    )


ignored_tokens = [
    token
    for token, _ in ranked_tokens
    if not is_protected_token(token)
][:DROP_TOP_N]
ignored_token_set = set(ignored_tokens)

vocabulary_tokens = [
    token
    for token, _ in ranked_tokens
    if token not in ignored_token_set
][:VOCAB_SIZE]

if len(vocabulary_tokens) < VOCAB_SIZE:
    raise ValueError("The training corpus contains fewer tokens than VOCAB_SIZE.")

PAD_TOKEN = "<pad>"
UNK_TOKEN = "<unk>"
PAD_ID = 0
UNK_ID = 1

id_to_token = [PAD_TOKEN, UNK_TOKEN] + vocabulary_tokens
token_to_id = {
    token: token_id
    for token_id, token in enumerate(id_to_token)
}
TOTAL_VOCAB_SIZE = len(id_to_token)

print("Ignored top-frequency tokens:", ignored_tokens[:50])
print("Embedding matrix rows:", TOTAL_VOCAB_SIZE)

Building vocabulary from 20,000 train reviews: 100%|██████████| 20000/20000 [00:02<00:00, 8419.23it/s]

Ignored top-frequency tokens: ['the', 'and', 'a', 'of', 'to', 'is', 'in', 'it', 'i', 'this', 'that', 'was', 'as', 'for', 'with', 'movie', 'film', 'on', 'you', 'his', 'are', 'have', 'he', 'be', 'one', 'all', 'at', 'by', 'an', 'they', 'who', 'from', 'her', 'or', 'about', "it's", 'out', 'if', 'has', 'there', 'some', 'what', 'when', 'up', 'even', 'time', 'she', 'my', 'would', 'which']
Embedding matrix rows: 8002

Encode documents

In [ ]:
def encode_documents(texts, description):
    encoded = []

    for text in tqdm(texts, desc=description):
        token_ids = [
            token_to_id[token]
            for token in tokenise(text)
            if token in token_to_id
        ]

        if not token_ids:
            token_ids = [UNK_ID]

        encoded.append(torch.tensor(token_ids, dtype=torch.long))

    return encoded


train_documents = encode_documents(
    train_dataset["text"],
    "Encoding labelled train reviews",
)
unlabelled_documents = encode_documents(
    unlabelled_dataset["text"],
    "Encoding unlabelled reviews",
)
train_labels = torch.tensor(
    train_dataset["label"],
    dtype=torch.long,
)
unlabelled_labels = torch.full(
    (len(unlabelled_documents),),
    -1,
    dtype=torch.long,
)

print("Labelled documents:", len(train_documents))
print("Unlabelled documents:", len(unlabelled_documents))

Encoding labelled train reviews: 100%|██████████| 20000/20000 [00:02<00:00, 8410.46it/s]
Encoding unlabelled reviews: 100%|██████████| 50000/50000 [00:04<00:00, 10836.67it/s]

Labelled documents: 20000
Unlabelled documents: 50000

In [ ]:
all_semantic_documents = train_documents + unlabelled_documents
all_semantic_labels = torch.cat(
    [train_labels, unlabelled_labels]
)

pretraining_specs = {
    "semantic_only": {
        "documents": train_documents,
        "labels": torch.full_like(train_labels, -1),
        "use_sentiment": False,
    },
    "semantic_sentiment": {
        "documents": train_documents,
        "labels": train_labels,
        "use_sentiment": True,
    },
    "semantic_sentiment_unlabeled": {
        "documents": all_semantic_documents,
        "labels": all_semantic_labels,
        "use_sentiment": True,
    },
}

group_summary = pd.DataFrame(
    [
        {
            "group": "random",
            "semantic_documents": 0,
            "sentiment_documents": 0,
        },
        {
            "group": "semantic_only",
            "semantic_documents": len(train_documents),
            "sentiment_documents": 0,
        },
        {
            "group": "semantic_sentiment",
            "semantic_documents": len(train_documents),
            "sentiment_documents": int((train_labels >= 0).sum()),
        },
        {
            "group": "semantic_sentiment_unlabeled",
            "semantic_documents": len(all_semantic_documents),
            "sentiment_documents": int((all_semantic_labels >= 0).sum()),
        },
    ]
)

group_summary

                          group  semantic_documents  sentiment_documents
0                        random                   0                    0
1                 semantic_only               20000                    0
2            semantic_sentiment               20000                20000
3  semantic_sentiment_unlabeled               70000                20000

In [ ]:
def make_initial_embedding():
    generator = torch.Generator().manual_seed(SEED)
    weights = torch.empty(TOTAL_VOCAB_SIZE, EMBED_DIM)
    weights.normal_(
        mean=0.0,
        std=EMBED_INIT_STD,
        generator=generator,
    )
    weights[PAD_ID].zero_()
    return weights


initial_embedding = make_initial_embedding()


class JointEmbeddingModel(nn.Module):
    def __init__(self, num_documents, initial_weights):
        super().__init__()
        document_generator = torch.Generator().manual_seed(
            SEED + 1
        )
        sentiment_generator = torch.Generator().manual_seed(
            SEED + 2
        )

        self.word_embeddings = nn.Embedding.from_pretrained(
            initial_weights.clone(),
            freeze=False,
            padding_idx=PAD_ID,
        )
        self.document_embeddings = nn.Embedding(
            num_documents,
            EMBED_DIM,
        )
        self.word_bias = nn.Embedding(
            TOTAL_VOCAB_SIZE,
            1,
            padding_idx=PAD_ID,
        )
        self.sentiment_head = nn.Linear(EMBED_DIM, 1)

        nn.init.normal_(
            self.document_embeddings.weight,
            mean=0.0,
            std=EMBED_INIT_STD,
            generator=document_generator,
        )
        nn.init.zeros_(self.word_bias.weight)
        nn.init.normal_(
            self.sentiment_head.weight,
            mean=0.0,
            std=EMBED_INIT_STD,
            generator=sentiment_generator,
        )
        nn.init.zeros_(self.sentiment_head.bias)


print("Initial embedding shape:", tuple(initial_embedding.shape))

Initial embedding shape: (8002, 50)

train embedding

In [ ]:
def build_batch_word_counts(
    documents,
    document_indices,
):
    batch_documents = [
        documents[index]
        for index in document_indices.tolist()
    ]

    vocabulary_ids = [
        document[document >= 2] - 2
        for document in batch_documents
    ]
    document_lengths = torch.tensor(
        [len(document) for document in vocabulary_ids],
        dtype=torch.long,
    )

    row_ids = torch.repeat_interleave(
        torch.arange(len(vocabulary_ids)),
        document_lengths,
    )
    word_ids = torch.cat(vocabulary_ids)
    flat_ids = row_ids * VOCAB_SIZE + word_ids

    return torch.bincount(
        flat_ids,
        minlength=len(vocabulary_ids) * VOCAB_SIZE,
    ).view(len(vocabulary_ids), VOCAB_SIZE).float()

In [ ]:
def train_embedding_group(
    group_name,
    documents,
    labels,
    use_sentiment,
):
    set_seed(SEED)

    model = JointEmbeddingModel(
        num_documents=len(documents),
        initial_weights=initial_embedding,
    ).to(device)
    initial_unk_vector = initial_embedding[UNK_ID].to(device)

    optimizer = torch.optim.AdamW(
        [
            {
                "params": model.word_embeddings.parameters(),
                "weight_decay": WEIGHT_DECAY,
            },
            {
                "params": model.document_embeddings.parameters(),
                "weight_decay": WEIGHT_DECAY,
            },
            {
                "params": model.word_bias.parameters(),
                "weight_decay": 0.0,
            },
            {
                "params": model.sentiment_head.parameters(),
                "weight_decay": 0.0,
            },
        ],
        lr=LEARNING_RATE,
    )

    loader_generator = torch.Generator().manual_seed(SEED)
    loader = DataLoader(
        TensorDataset(
            torch.arange(len(documents)),
            labels,
        ),
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=NUM_WORKERS,
        generator=loader_generator,
    )

    history = []
    best_training_loss = float("inf")
    best_patience_loss = float("inf")
    best_training_epoch = None
    best_word_weights = None
    best_sentiment_weight = None
    best_sentiment_bias = None
    epochs_without_improvement = 0
    stopped_early = False

    for epoch in range(1, MAX_EPOCHS + 1):
        model.train()

        total_semantic_nll = 0.0
        total_sentiment_nll = 0.0
        total_tokens = 0

        progress = tqdm(
            loader,
            desc=f"{group_name} | epoch {epoch}",
            leave=False,
        )

        for document_indices, batch_labels in progress:
            batch_word_counts = build_batch_word_counts(
                documents,
                document_indices,
            )
            batch_token_count = int(
                batch_word_counts.sum().item()
            )

            if batch_token_count == 0:
                continue

            document_indices = document_indices.to(device)
            batch_labels = batch_labels.to(device)
            batch_word_counts = batch_word_counts.to(device)

            document_vectors = model.document_embeddings(
                document_indices
            )
            word_vectors = model.word_embeddings.weight[2:]
            word_bias = model.word_bias.weight[2:].squeeze(-1)

            semantic_logits = (
                document_vectors @ word_vectors.T
                + word_bias
            )
            semantic_log_probs = F.log_softmax(
                semantic_logits,
                dim=1,
            )
            semantic_nll = -(
                batch_word_counts * semantic_log_probs
            ).sum()
            semantic_loss = (
                semantic_nll / batch_token_count
            )

            sentiment_nll = torch.zeros(
                (),
                device=device,
            )

            labelled_mask = batch_labels >= 0
            if use_sentiment and labelled_mask.any():
                labelled_counts = batch_word_counts[
                    labelled_mask
                ]
                labelled_labels = batch_labels[
                    labelled_mask
                ].float()

                positive_counts = (
                    labelled_counts
                    * labelled_labels.unsqueeze(1)
                ).sum(dim=0)
                negative_counts = (
                    labelled_counts
                    * (1.0 - labelled_labels).unsqueeze(1)
                ).sum(dim=0)

                sentiment_logits = model.sentiment_head(
                    word_vectors
                ).squeeze(-1)
                sentiment_nll = (
                    F.softplus(-sentiment_logits)
                    * positive_counts
                    + F.softplus(sentiment_logits)
                    * negative_counts
                ).sum()

            sentiment_loss = (
                sentiment_nll / batch_token_count
            )

            loss = (
                semantic_loss
                + SENTIMENT_WEIGHT * sentiment_loss
            )

            optimizer.zero_grad()
            loss.backward()

            torch.nn.utils.clip_grad_norm_(
                model.parameters(),
                GRAD_CLIP,
            )

            optimizer.step()

            with torch.no_grad():
                model.word_embeddings.weight[PAD_ID].zero_()
                model.word_embeddings.weight[UNK_ID].copy_(
                    initial_unk_vector
                )

            total_semantic_nll += semantic_nll.item()
            total_sentiment_nll += sentiment_nll.item()
            total_tokens += batch_token_count

        epoch_record = {
            "group": group_name,
            "epoch": epoch,
            "loss": (
                total_semantic_nll
                + SENTIMENT_WEIGHT * total_sentiment_nll
            ) / total_tokens,
            "semantic_loss": (
                total_semantic_nll / total_tokens
            ),
            "sentiment_loss": (
                total_sentiment_nll / total_tokens
            ),
        }
        history.append(epoch_record)

        current_loss = epoch_record["loss"]
        is_lowest_training_loss = (
            current_loss < best_training_loss
        )
        if is_lowest_training_loss:
            best_training_loss = current_loss
            best_training_epoch = epoch
            best_word_weights = (
                model.word_embeddings.weight
                .detach()
                .cpu()
                .clone()
            )

            if use_sentiment:
                best_sentiment_weight = (
                    model.sentiment_head.weight
                    .detach()
                    .cpu()
                    .clone()
                )
                best_sentiment_bias = (
                    model.sentiment_head.bias
                    .detach()
                    .cpu()
                    .clone()
                )

        is_meaningful_improvement = (
            current_loss
            < best_patience_loss
            - EARLY_STOPPING_MIN_DELTA
        )
        if is_meaningful_improvement:
            best_patience_loss = current_loss
            epochs_without_improvement = 0
        else:
            epochs_without_improvement += 1

        print(
            f"{group_name} | epoch {epoch:02d} | "
            f"semantic={epoch_record['semantic_loss']:.4f} | "
            f"sentiment={epoch_record['sentiment_loss']:.4f} | "
            f"total={current_loss:.4f}"
            + (
                " | lowest training objective so far"
                if is_lowest_training_loss
                else ""
            )
            + (
                f" | early_stop={epochs_without_improvement}"
                f"/{EARLY_STOPPING_PATIENCE}"
            )
        )

        if (
            epochs_without_improvement
            >= EARLY_STOPPING_PATIENCE
        ):
            stopped_early = True
            print(
                f"{group_name} | early stopping at epoch "
                f"{epoch:02d}: no improvement >= "
                f"{EARLY_STOPPING_MIN_DELTA:g} for "
                f"{EARLY_STOPPING_PATIENCE} epochs"
            )
            break

    print(
        f"{group_name} | selected best Embedding: "
        f"epoch {best_training_epoch:02d} "
        f"(loss={best_training_loss:.4f}); "
        f"trained {len(history)} epoch(s)"
    )

    result = {
        "weight": best_word_weights,
        "best_training_epoch": best_training_epoch,
        "best_training_loss": best_training_loss,
        "epochs_trained": len(history),
        "stopped_early": stopped_early,
        "sentiment_weight": best_sentiment_weight,
        "sentiment_bias": best_sentiment_bias,
    }

    del model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return result, history

In [ ]:
embedding_results = {
    "random": {
        "weight": initial_embedding.clone(),
        "best_training_epoch": 0,
        "best_training_loss": None,
        "epochs_trained": 0,
        "stopped_early": False,
        "sentiment_weight": None,
        "sentiment_bias": None,
    }
}
history_rows = []

for group_name, spec in pretraining_specs.items():
    print("\n" + "=" * 70)
    print(group_name)
    print("=" * 70)

    group_result, group_history = train_embedding_group(
        group_name=group_name,
        documents=spec["documents"],
        labels=spec["labels"],
        use_sentiment=spec["use_sentiment"],
    )

    embedding_results[group_name] = group_result
    history_rows.extend(group_history)

history_df = pd.DataFrame(history_rows)
history_df

======================================================================
semantic_only
======================================================================

semantic_only | epoch 01 | semantic=8.9070 | sentiment=0.0000 | total=8.9070 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 02 | semantic=8.7155 | sentiment=0.0000 | total=8.7155 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 03 | semantic=8.2914 | sentiment=0.0000 | total=8.2914 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 04 | semantic=7.8112 | sentiment=0.0000 | total=7.8112 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 05 | semantic=7.7020 | sentiment=0.0000 | total=7.7020 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 06 | semantic=7.6874 | sentiment=0.0000 | total=7.6874 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 07 | semantic=7.6824 | sentiment=0.0000 | total=7.6824 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 08 | semantic=7.6772 | sentiment=0.0000 | total=7.6772 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 09 | semantic=7.6699 | sentiment=0.0000 | total=7.6699 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 10 | semantic=7.6590 | sentiment=0.0000 | total=7.6590 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 11 | semantic=7.6432 | sentiment=0.0000 | total=7.6432 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 12 | semantic=7.6218 | sentiment=0.0000 | total=7.6218 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 13 | semantic=7.5958 | sentiment=0.0000 | total=7.5958 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 14 | semantic=7.5663 | sentiment=0.0000 | total=7.5663 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 15 | semantic=7.5350 | sentiment=0.0000 | total=7.5350 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 16 | semantic=7.5019 | sentiment=0.0000 | total=7.5019 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 17 | semantic=7.4678 | sentiment=0.0000 | total=7.4678 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 18 | semantic=7.4327 | sentiment=0.0000 | total=7.4327 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 19 | semantic=7.3971 | sentiment=0.0000 | total=7.3971 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 20 | semantic=7.3613 | sentiment=0.0000 | total=7.3613 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 21 | semantic=7.3251 | sentiment=0.0000 | total=7.3251 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 22 | semantic=7.2897 | sentiment=0.0000 | total=7.2897 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 23 | semantic=7.2553 | sentiment=0.0000 | total=7.2553 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 24 | semantic=7.2225 | sentiment=0.0000 | total=7.2225 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 25 | semantic=7.1914 | sentiment=0.0000 | total=7.1914 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 26 | semantic=7.1628 | sentiment=0.0000 | total=7.1628 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 27 | semantic=7.1364 | sentiment=0.0000 | total=7.1364 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 28 | semantic=7.1128 | sentiment=0.0000 | total=7.1128 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 29 | semantic=7.0914 | sentiment=0.0000 | total=7.0914 | lowest training objective so far | early_stop=0/4

semantic_only | epoch 30 | semantic=7.0722 | sentiment=0.0000 | total=7.0722 | lowest training objective so far | early_stop=0/4
semantic_only | selected best Embedding: epoch 30 (loss=7.0722); trained 30 epoch(s)

======================================================================
semantic_sentiment
======================================================================

semantic_sentiment | epoch 01 | semantic=8.9070 | sentiment=0.6840 | total=9.5910 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 02 | semantic=8.7391 | sentiment=0.6699 | total=9.4090 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 03 | semantic=8.5051 | sentiment=0.6681 | total=9.1732 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 04 | semantic=8.0860 | sentiment=0.6679 | total=8.7538 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 05 | semantic=7.7393 | sentiment=0.6676 | total=8.4069 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 06 | semantic=7.6754 | sentiment=0.6671 | total=8.3425 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 07 | semantic=7.6577 | sentiment=0.6669 | total=8.3246 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 08 | semantic=7.6473 | sentiment=0.6667 | total=8.3140 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 09 | semantic=7.6393 | sentiment=0.6666 | total=8.3059 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 10 | semantic=7.6324 | sentiment=0.6665 | total=8.2988 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 11 | semantic=7.6251 | sentiment=0.6664 | total=8.2914 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 12 | semantic=7.6163 | sentiment=0.6662 | total=8.2825 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 13 | semantic=7.6050 | sentiment=0.6663 | total=8.2713 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 14 | semantic=7.5904 | sentiment=0.6668 | total=8.2571 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 15 | semantic=7.5717 | sentiment=0.6665 | total=8.2382 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 16 | semantic=7.5487 | sentiment=0.6663 | total=8.2151 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 17 | semantic=7.5221 | sentiment=0.6663 | total=8.1884 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 18 | semantic=7.4923 | sentiment=0.6661 | total=8.1585 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 19 | semantic=7.4604 | sentiment=0.6661 | total=8.1265 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 20 | semantic=7.4271 | sentiment=0.6663 | total=8.0933 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 21 | semantic=7.3927 | sentiment=0.6662 | total=8.0589 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 22 | semantic=7.3579 | sentiment=0.6661 | total=8.0241 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 23 | semantic=7.3233 | sentiment=0.6661 | total=7.9895 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 24 | semantic=7.2893 | sentiment=0.6661 | total=7.9554 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 25 | semantic=7.2562 | sentiment=0.6662 | total=7.9224 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 26 | semantic=7.2245 | sentiment=0.6661 | total=7.8907 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 27 | semantic=7.1946 | sentiment=0.6661 | total=7.8607 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 28 | semantic=7.1664 | sentiment=0.6661 | total=7.8326 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 29 | semantic=7.1404 | sentiment=0.6661 | total=7.8065 | lowest training objective so far | early_stop=0/4

semantic_sentiment | epoch 30 | semantic=7.1163 | sentiment=0.6661 | total=7.7825 | lowest training objective so far | early_stop=0/4
semantic_sentiment | selected best Embedding: epoch 30 (loss=7.7825); trained 30 epoch(s)

======================================================================
semantic_sentiment_unlabeled
======================================================================

semantic_sentiment_unlabeled | epoch 01 | semantic=8.7234 | sentiment=0.1947 | total=8.9181 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 02 | semantic=8.2257 | sentiment=0.1926 | total=8.4183 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 03 | semantic=7.7087 | sentiment=0.1924 | total=7.9011 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 04 | semantic=7.6557 | sentiment=0.1919 | total=7.8477 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 05 | semantic=7.6278 | sentiment=0.1918 | total=7.8196 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 06 | semantic=7.5928 | sentiment=0.1917 | total=7.7845 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 07 | semantic=7.5414 | sentiment=0.1917 | total=7.7331 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 08 | semantic=7.4794 | sentiment=0.1916 | total=7.6710 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 09 | semantic=7.4154 | sentiment=0.1916 | total=7.6070 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 10 | semantic=7.3533 | sentiment=0.1916 | total=7.5449 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 11 | semantic=7.2952 | sentiment=0.1917 | total=7.4869 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 12 | semantic=7.2432 | sentiment=0.1917 | total=7.4349 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 13 | semantic=7.1985 | sentiment=0.1917 | total=7.3902 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 14 | semantic=7.1612 | sentiment=0.1916 | total=7.3528 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 15 | semantic=7.1305 | sentiment=0.1917 | total=7.3222 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 16 | semantic=7.1053 | sentiment=0.1917 | total=7.2969 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 17 | semantic=7.0844 | sentiment=0.1917 | total=7.2761 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 18 | semantic=7.0669 | sentiment=0.1917 | total=7.2585 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 19 | semantic=7.0521 | sentiment=0.1917 | total=7.2438 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 20 | semantic=7.0397 | sentiment=0.1917 | total=7.2314 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 21 | semantic=7.0291 | sentiment=0.1917 | total=7.2208 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 22 | semantic=7.0199 | sentiment=0.1917 | total=7.2116 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 23 | semantic=7.0116 | sentiment=0.1917 | total=7.2033 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 24 | semantic=7.0038 | sentiment=0.1917 | total=7.1955 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 25 | semantic=6.9965 | sentiment=0.1917 | total=7.1882 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 26 | semantic=6.9899 | sentiment=0.1917 | total=7.1816 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 27 | semantic=6.9838 | sentiment=0.1917 | total=7.1755 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 28 | semantic=6.9782 | sentiment=0.1917 | total=7.1699 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 29 | semantic=6.9733 | sentiment=0.1917 | total=7.1650 | lowest training objective so far | early_stop=0/4

semantic_sentiment_unlabeled | epoch 30 | semantic=6.9686 | sentiment=0.1917 | total=7.1603 | lowest training objective so far | early_stop=0/4
semantic_sentiment_unlabeled | selected best Embedding: epoch 30 (loss=7.1603); trained 30 epoch(s)

,group,epoch,loss,semantic_loss,sentiment_loss
0,semantic_only,1,8.907041,8.907041,0.000000
1,semantic_only,2,8.715535,8.715535,0.000000
2,semantic_only,3,8.291359,8.291359,0.000000
3,semantic_only,4,7.811232,7.811232,0.000000
4,semantic_only,5,7.701996,7.701996,0.000000
...,...,...,...,...,...
85,semantic_sentiment_unlabeled,26,7.181562,6.989874,0.191687
86,semantic_sentiment_unlabeled,27,7.175475,6.983792,0.191683
87,semantic_sentiment_unlabeled,28,7.169949,6.978248,0.191701
88,semantic_sentiment_unlabeled,29,7.164958,6.973272,0.191686
89,semantic_sentiment_unlabeled,30,7.160340,6.968629,0.191710

In [ ]:
#save
from pathlib import Path

EMBEDDING_SAVE_PATH = Path("./model/four_embedding_results.pt")

GROUP_NAMES = [
    "random",
    "semantic_only",
    "semantic_sentiment",
    "semantic_sentiment_unlabeled",
]

checkpoint = {
    "embedding_results": {
        group_name: {
            key: (
                value.detach().cpu().clone()
                if torch.is_tensor(value)
                else value
            )
            for key, value in embedding_results[group_name].items()
        }
        for group_name in GROUP_NAMES
    },
    "id_to_token": id_to_token,
    "token_to_id": token_to_id,
    "pad_id": PAD_ID,
    "unk_id": UNK_ID,

    "total_vocab_size": TOTAL_VOCAB_SIZE,
    "embed_dim": EMBED_DIM,
    "seed": SEED,
}

torch.save(checkpoint, EMBEDDING_SAVE_PATH)

print(f"Saved to: {EMBEDDING_SAVE_PATH.resolve()}")

for group_name in GROUP_NAMES:
    result = checkpoint["embedding_results"][group_name]
    print(
        f"{group_name:34s} "
        f"shape={tuple(result['weight'].shape)} | "
        f"best_epoch={result['best_training_epoch']}"
    )

Saved to: C:\Users\lulu\Desktop\9444\ASSISMENT\model\four_embedding_results.pt
random                             shape=(8002, 50) | best_epoch=0
semantic_only                      shape=(8002, 50) | best_epoch=30
semantic_sentiment                 shape=(8002, 50) | best_epoch=30
semantic_sentiment_unlabeled       shape=(8002, 50) | best_epoch=30

In [ ]:
for group_name, result in embedding_results.items():
    weights = result["weight"]

    distance_from_initial = torch.linalg.vector_norm(
        weights - initial_embedding
    ).item()

    print(
        f"{group_name:34s} "
        f"epoch={result['best_training_epoch']:02d} "
        f"trained={result['epochs_trained']:02d} "
        f"early_stopped={result['stopped_early']} "
        f"shape={tuple(weights.shape)} "
        f"distance_from_initial={distance_from_initial:.4f}"
    )

random                             epoch=00 trained=00 early_stopped=False shape=(8002, 50) distance_from_initial=0.0000
semantic_only                      epoch=30 trained=30 early_stopped=False shape=(8002, 50) distance_from_initial=462.1321
semantic_sentiment                 epoch=30 trained=30 early_stopped=False shape=(8002, 50) distance_from_initial=355.8790
semantic_sentiment_unlabeled       epoch=30 trained=30 early_stopped=False shape=(8002, 50) distance_from_initial=592.1082

### Inspect learned Embeddings

In [ ]:
def nearest_words(
    group_name,
    query_word,
    top_k=8,
):
    if query_word not in token_to_id:
        return []

    weights = embedding_results[group_name]["weight"]
    normalised = F.normalize(
        weights[2:],
        p=2,
        dim=1,
    )

    query_id = token_to_id[query_word]
    query_vector = F.normalize(
        weights[query_id].unsqueeze(0),
        p=2,
        dim=1,
    )

    similarities = normalised @ query_vector.squeeze(0)
    similarities[query_id - 2] = -torch.inf

    neighbour_positions = torch.topk(
        similarities,
        k=top_k,
    ).indices

    return [
        id_to_token[position.item() + 2]
        for position in neighbour_positions
    ]


for query_word in ["excellent", "awful", "boring"]:
    if query_word not in token_to_id:
        continue

    print(f"\nQuery: {query_word}")
    for group_name in sorted(embedding_results):
        print(
            f"{group_name:34s}",
            nearest_words(group_name, query_word),
        )

Query: excellent
random                             ['wondered', 'phil', 'window', 'gritty', 'obnoxious', 'integrity', 'nights', 'cooper']
semantic_only                      ['superb', 'perfect', 'rate', 'outstanding', 'highly', 'strong', 'impressed', 'underrated']
semantic_sentiment                 ['superb', 'outstanding', 'brilliant', 'underrated', 'rate', 'fantastic', 'highly', 'performances']
semantic_sentiment_unlabeled       ['outstanding', 'superb', 'exceptional', 'superbly', 'flawless', 'fantastic', 'highly', 'recommended']

Query: awful
random                             ['clown', 'challenges', 'goals', 'juan', 'pizza', 'millions', 'sole', 'tramp']
semantic_only                      ['waste', 'redeeming', 'lousy', 'worst', 'atrocious', 'pathetic', 'terrible', 'horrible']
semantic_sentiment                 ['terrible', 'waste', 'amateur', 'worst', 'dreadful', 'wasted', 'poorly', 'costs']
semantic_sentiment_unlabeled       ['terrible', 'avoid', 'lousy', 'dreadful', 'laughable', 'atrocious', 'horribly', 'costs']

Query: boring
random                             ['end', 'burned', 'water', 'generous', 'key', 'numbing', 'pot', 'exist']
semantic_only                      ['predictable', 'overrated', 'uninteresting', 'pointless', 'asleep', 'waste', 'bored', 'tedious']
semantic_sentiment                 ['clich', 'predictable', 'bored', 'pointless', 'unrealistic', 'annoying', 'overrated', 'uninteresting']
semantic_sentiment_unlabeled       ['dull', 'uninteresting', 'bored', 'slow', 'annoying', 'pointless', 'tedious', 'bland']

## CNN

simple one just for result

In [ ]:
# CNN hyperparameters
CNN_MAX_LENGTH = 1000
CNN_FILTERS = 1000
CNN_KERNEL_SIZE = 4
CNN_DROPOUT = 0.5
CNN_BATCH_SIZE = 128
CNN_MAX_EPOCHS = 15
CNN_EARLY_STOPPING_PATIENCE = 3
CNN_EARLY_STOPPING_MIN_DELTA = 1e-4
CNN_LEARNING_RATE = 1e-3
CNN_WEIGHT_DECAY = 1e-4
CNN_GRAD_CLIP = 5.0
CNN_FREEZE_EMBEDDING = False
CNN_NUM_WORKERS = 0

CNN_GROUPS = [
    "random",
    "semantic_only",
    "semantic_sentiment",
    "semantic_sentiment_unlabeled",
]

if torch.cuda.is_available():
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

In [ ]:
from torch.utils.data import Dataset


valid_documents = encode_documents(
    valid_dataset["text"],
    "Encoding validation reviews",
)
test_documents = encode_documents(
    test_dataset["text"],
    "Encoding test reviews",
)

valid_labels = torch.tensor(
    valid_dataset["label"],
    dtype=torch.long,
)
test_labels = torch.tensor(
    test_dataset["label"],
    dtype=torch.long,
)


class ReviewDataset(Dataset):
    def __init__(self, documents, labels):
        self.documents = documents
        self.labels = labels

    def __len__(self):
        return len(self.documents)

    def __getitem__(self, index):
        return self.documents[index], self.labels[index]


def collate_reviews(batch):
    documents, labels = zip(*batch)
    documents = [
        document[:CNN_MAX_LENGTH]
        for document in documents
    ]
    lengths = torch.tensor(
        [len(document) for document in documents],
        dtype=torch.long,
    )
    padded_length = max(
        CNN_KERNEL_SIZE,
        int(lengths.max()),
    )
    input_ids = torch.full(
        (len(documents), padded_length),
        PAD_ID,
        dtype=torch.long,
    )

    for row, document in enumerate(documents):
        input_ids[row, :len(document)] = document

    labels = torch.tensor(
        [int(label) for label in labels],
        dtype=torch.long,
    )
    return input_ids, lengths, labels


train_review_dataset = ReviewDataset(
    train_documents,
    train_labels,
)
valid_review_dataset = ReviewDataset(
    valid_documents,
    valid_labels,
)
test_review_dataset = ReviewDataset(
    test_documents,
    test_labels,
)


def make_cnn_loader(dataset, shuffle):
    generator = (
        torch.Generator().manual_seed(SEED)
        if shuffle
        else None
    )
    return DataLoader(
        dataset,
        batch_size=CNN_BATCH_SIZE,
        shuffle=shuffle,
        num_workers=CNN_NUM_WORKERS,
        collate_fn=collate_reviews,
        pin_memory=(device.type == "cuda"),
        generator=generator,
    )


valid_loader = make_cnn_loader(
    valid_review_dataset,
    shuffle=False,
)
test_loader = make_cnn_loader(
    test_review_dataset,
    shuffle=False,
)

print(
    f"CNN data: train={len(train_review_dataset):,}, "
    f"validation={len(valid_review_dataset):,}, "
    f"test={len(test_review_dataset):,}"
)

Encoding validation reviews: 100%|██████████| 5000/5000 [00:00<00:00, 9659.63it/s]
Encoding test reviews: 100%|██████████| 25000/25000 [00:02<00:00, 12187.09it/s]

CNN data: train=20,000, validation=5,000, test=25,000

In [ ]:
class SimpleTextCNN(nn.Module):
    def __init__(self, embedding_weights):
        super().__init__()

        self.embedding = nn.Embedding.from_pretrained(
            embedding_weights.clone(),
            freeze=CNN_FREEZE_EMBEDDING,
            padding_idx=PAD_ID,
        )
        self.convolution = nn.Conv1d(
            in_channels=EMBED_DIM,
            out_channels=CNN_FILTERS,
            kernel_size=CNN_KERNEL_SIZE,
        )
        self.dropout = nn.Dropout(CNN_DROPOUT)
        self.classifier = nn.Linear(CNN_FILTERS, 1)

    def forward(self, input_ids, lengths):
        embedded = self.embedding(input_ids)
        embedded = embedded.transpose(1, 2)

        features = F.relu(
            self.convolution(embedded)
        )

        valid_steps = (
            lengths - CNN_KERNEL_SIZE + 1
        ).clamp(min=1)
        positions = torch.arange(
            features.size(2),
            device=features.device,
        ).unsqueeze(0)
        padding_mask = positions >= valid_steps.unsqueeze(1)
        features = features.masked_fill(
            padding_mask.unsqueeze(1),
            -torch.inf,
        )

        pooled = features.max(dim=2).values
        logits = self.classifier(
            self.dropout(pooled)
        )
        return logits.squeeze(1)

In [ ]:
def binary_metrics(labels, predictions):
    true_positive = int(
        ((labels == 1) & (predictions == 1)).sum()
    )
    true_negative = int(
        ((labels == 0) & (predictions == 0)).sum()
    )
    false_positive = int(
        ((labels == 0) & (predictions == 1)).sum()
    )
    false_negative = int(
        ((labels == 1) & (predictions == 0)).sum()
    )

    total = len(labels)
    accuracy = (true_positive + true_negative) / total
    precision = (
        true_positive / (true_positive + false_positive)
        if true_positive + false_positive > 0
        else 0.0
    )
    recall = (
        true_positive / (true_positive + false_negative)
        if true_positive + false_negative > 0
        else 0.0
    )
    f1 = (
        2 * precision * recall / (precision + recall)
        if precision + recall > 0
        else 0.0
    )

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1,
    }


@torch.inference_mode()
def evaluate_cnn(model, loader):
    model.eval()
    criterion = nn.BCEWithLogitsLoss(reduction="sum")

    total_loss = 0.0
    all_labels = []
    all_predictions = []

    for input_ids, lengths, labels in loader:
        input_ids = input_ids.to(device)
        lengths = lengths.to(device)
        labels = labels.to(device)

        logits = model(input_ids, lengths)
        total_loss += criterion(
            logits,
            labels.float(),
        ).item()

        predictions = (logits >= 0).long()
        all_labels.append(labels.cpu())
        all_predictions.append(predictions.cpu())

    all_labels = torch.cat(all_labels)
    all_predictions = torch.cat(all_predictions)

    metrics = binary_metrics(
        all_labels,
        all_predictions,
    )
    metrics["loss"] = total_loss / len(all_labels)
    return metrics

In [ ]:
def train_cnn_group(group_name):
    set_seed(SEED)

    train_loader = make_cnn_loader(
        train_review_dataset,
        shuffle=True,
    )
    model = SimpleTextCNN(
        embedding_results[group_name]["weight"]
    ).to(device)

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=CNN_LEARNING_RATE,
        weight_decay=CNN_WEIGHT_DECAY,
    )
    criterion = nn.BCEWithLogitsLoss()

    best_validation_f1 = -float("inf")
    best_patience_f1 = -float("inf")
    best_epoch = None
    best_state = None
    epochs_without_improvement = 0
    stopped_early = False
    history = []

    for epoch in range(1, CNN_MAX_EPOCHS + 1):
        model.train()
        total_train_loss = 0.0
        total_train_examples = 0

        progress = tqdm(
            train_loader,
            desc=f"{group_name} | CNN epoch {epoch}",
            leave=False,
        )

        for input_ids, lengths, labels in progress:
            input_ids = input_ids.to(device)
            lengths = lengths.to(device)
            labels = labels.to(device)

            logits = model(input_ids, lengths)
            loss = criterion(logits, labels.float())

            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(
                model.parameters(),
                CNN_GRAD_CLIP,
            )
            optimizer.step()

            batch_size = len(labels)
            total_train_loss += loss.item() * batch_size
            total_train_examples += batch_size

        validation_metrics = evaluate_cnn(
            model,
            valid_loader,
        )
        train_loss = (
            total_train_loss / total_train_examples
        )
        current_f1 = validation_metrics["f1"]

        history.append(
            {
                "group": group_name,
                "epoch": epoch,
                "train_loss": train_loss,
                "validation_loss": validation_metrics["loss"],
                "validation_accuracy": validation_metrics["accuracy"],
                "validation_precision": validation_metrics["precision"],
                "validation_recall": validation_metrics["recall"],
                "validation_f1": current_f1,
            }
        )

        is_best = current_f1 > best_validation_f1
        if is_best:
            best_validation_f1 = current_f1
            best_epoch = epoch
            best_state = {
                name: value.detach().cpu().clone()
                for name, value in model.state_dict().items()
            }

        is_meaningful_improvement = (
            current_f1
            > best_patience_f1
            + CNN_EARLY_STOPPING_MIN_DELTA
        )
        if is_meaningful_improvement:
            best_patience_f1 = current_f1
            epochs_without_improvement = 0
        else:
            epochs_without_improvement += 1

        print(
            f"{group_name:34s} | epoch {epoch:02d} | "
            f"train loss={train_loss:.4f} | "
            f"val acc={validation_metrics['accuracy']:.4f} | "
            f"val P={validation_metrics['precision']:.4f} | "
            f"val R={validation_metrics['recall']:.4f} | "
            f"val F1={current_f1:.4f}"
            + (" | best" if is_best else "")
            + (
                f" | early_stop={epochs_without_improvement}"
                f"/{CNN_EARLY_STOPPING_PATIENCE}"
            )
        )

        if (
            epochs_without_improvement
            >= CNN_EARLY_STOPPING_PATIENCE
        ):
            stopped_early = True
            break

    model.load_state_dict(best_state)
    validation_metrics = evaluate_cnn(model, valid_loader)
    test_metrics = evaluate_cnn(model, test_loader)

    result = {
        "group": group_name,
        "best_epoch": best_epoch,
        "epochs_trained": len(history),
        "early_stopped": stopped_early,
        "validation_accuracy": validation_metrics["accuracy"],
        "validation_precision": validation_metrics["precision"],
        "validation_recall": validation_metrics["recall"],
        "validation_f1": validation_metrics["f1"],
        "test_accuracy": test_metrics["accuracy"],
        "test_precision": test_metrics["precision"],
        "test_recall": test_metrics["recall"],
        "test_f1": test_metrics["f1"],
    }

    del model
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return result, history

In [ ]:
cnn_results = []
cnn_history_rows = []

for group_name in CNN_GROUPS:
    print("\n" + "=" * 70)
    print(group_name)
    print("=" * 70)

    group_result, group_history = train_cnn_group(
        group_name
    )
    cnn_results.append(group_result)
    cnn_history_rows.extend(group_history)

    print(
        f"{group_name} | selected CNN epoch "
        f"{group_result['best_epoch']:02d} | "
        f"test acc={group_result['test_accuracy']:.4f} | "
        f"test P={group_result['test_precision']:.4f} | "
        f"test R={group_result['test_recall']:.4f} | "
        f"test F1={group_result['test_f1']:.4f}"
    )

cnn_results_df = pd.DataFrame(cnn_results)
cnn_history_df = pd.DataFrame(cnn_history_rows)
cnn_results_df.round(4)

======================================================================
random
======================================================================

random                             | epoch 01 | train loss=0.5272 | val acc=0.8436 | val P=0.8420 | val R=0.8460 | val F1=0.8440 | best | early_stop=0/3

random                             | epoch 02 | train loss=0.2832 | val acc=0.8542 | val P=0.8619 | val R=0.8436 | val F1=0.8526 | best | early_stop=0/3

random                             | epoch 03 | train loss=0.1948 | val acc=0.8532 | val P=0.8496 | val R=0.8584 | val F1=0.8540 | best | early_stop=0/3

random                             | epoch 04 | train loss=0.1307 | val acc=0.8496 | val P=0.8559 | val R=0.8408 | val F1=0.8483 | early_stop=1/3

random                             | epoch 05 | train loss=0.0782 | val acc=0.8398 | val P=0.8325 | val R=0.8508 | val F1=0.8415 | early_stop=2/3

random                             | epoch 06 | train loss=0.0437 | val acc=0.8410 | val P=0.8442 | val R=0.8364 | val F1=0.8403 | early_stop=3/3
random | selected CNN epoch 03 | test acc=0.8544 | test P=0.8534 | test R=0.8559 | test F1=0.8547

======================================================================
semantic_only
======================================================================

semantic_only                      | epoch 01 | train loss=0.4207 | val acc=0.8638 | val P=0.8289 | val R=0.9168 | val F1=0.8707 | best | early_stop=0/3

semantic_only                      | epoch 02 | train loss=0.3004 | val acc=0.8822 | val P=0.8790 | val R=0.8864 | val F1=0.8827 | best | early_stop=0/3

semantic_only                      | epoch 03 | train loss=0.2657 | val acc=0.8798 | val P=0.8534 | val R=0.9172 | val F1=0.8841 | best | early_stop=0/3

semantic_only                      | epoch 04 | train loss=0.2347 | val acc=0.8880 | val P=0.8783 | val R=0.9008 | val F1=0.8894 | best | early_stop=0/3

semantic_only                      | epoch 05 | train loss=0.2114 | val acc=0.8868 | val P=0.8890 | val R=0.8840 | val F1=0.8865 | early_stop=1/3

semantic_only                      | epoch 06 | train loss=0.1869 | val acc=0.8808 | val P=0.9003 | val R=0.8564 | val F1=0.8778 | early_stop=2/3

semantic_only                      | epoch 07 | train loss=0.1646 | val acc=0.8720 | val P=0.8286 | val R=0.9380 | val F1=0.8799 | early_stop=3/3
semantic_only | selected CNN epoch 04 | test acc=0.8849 | test P=0.8752 | test R=0.8978 | test F1=0.8863

======================================================================
semantic_sentiment
======================================================================

semantic_sentiment                 | epoch 01 | train loss=0.3660 | val acc=0.8726 | val P=0.8451 | val R=0.9124 | val F1=0.8775 | best | early_stop=0/3

semantic_sentiment                 | epoch 02 | train loss=0.2570 | val acc=0.8818 | val P=0.8795 | val R=0.8848 | val F1=0.8822 | best | early_stop=0/3

semantic_sentiment                 | epoch 03 | train loss=0.2281 | val acc=0.8832 | val P=0.8662 | val R=0.9064 | val F1=0.8858 | best | early_stop=0/3

semantic_sentiment                 | epoch 04 | train loss=0.1963 | val acc=0.8862 | val P=0.8968 | val R=0.8728 | val F1=0.8847 | early_stop=1/3

semantic_sentiment                 | epoch 05 | train loss=0.1729 | val acc=0.8842 | val P=0.8897 | val R=0.8772 | val F1=0.8834 | early_stop=2/3

semantic_sentiment                 | epoch 06 | train loss=0.1511 | val acc=0.8822 | val P=0.8895 | val R=0.8728 | val F1=0.8811 | early_stop=3/3
semantic_sentiment | selected CNN epoch 03 | test acc=0.8772 | test P=0.8618 | test R=0.8985 | test F1=0.8798

======================================================================
semantic_sentiment_unlabeled
======================================================================

semantic_sentiment_unlabeled       | epoch 01 | train loss=0.3799 | val acc=0.8738 | val P=0.8475 | val R=0.9116 | val F1=0.8784 | best | early_stop=0/3

semantic_sentiment_unlabeled       | epoch 02 | train loss=0.2655 | val acc=0.8808 | val P=0.8811 | val R=0.8804 | val F1=0.8808 | best | early_stop=0/3

semantic_sentiment_unlabeled       | epoch 03 | train loss=0.2362 | val acc=0.8858 | val P=0.8731 | val R=0.9028 | val F1=0.8877 | best | early_stop=0/3

semantic_sentiment_unlabeled       | epoch 04 | train loss=0.2064 | val acc=0.8872 | val P=0.8925 | val R=0.8804 | val F1=0.8864 | early_stop=1/3

semantic_sentiment_unlabeled       | epoch 05 | train loss=0.1887 | val acc=0.8852 | val P=0.8889 | val R=0.8804 | val F1=0.8846 | early_stop=2/3

semantic_sentiment_unlabeled       | epoch 06 | train loss=0.1692 | val acc=0.8850 | val P=0.8901 | val R=0.8784 | val F1=0.8842 | early_stop=3/3
semantic_sentiment_unlabeled | selected CNN epoch 03 | test acc=0.8863 | test P=0.8722 | test R=0.9053 | test F1=0.8884

,group,best_epoch,epochs_trained,early_stopped,validation_accuracy,validation_precision,validation_recall,validation_f1,test_accuracy,test_precision,test_recall,test_f1
0,random,3,6,True,0.8532,0.8496,0.8584,0.8540,0.8544,0.8534,0.8559,0.8547
1,semantic_only,4,7,True,0.8880,0.8783,0.9008,0.8894,0.8849,0.8752,0.8978,0.8863
2,semantic_sentiment,3,6,True,0.8832,0.8662,0.9064,0.8858,0.8772,0.8618,0.8985,0.8798
3,semantic_sentiment_unlabeled,3,6,True,0.8858,0.8731,0.9028,0.8877,0.8863,0.8722,0.9053,0.8884

## Compare

In [ ]:
random_result = cnn_results_df.loc[
    cnn_results_df["group"] == "random"
].iloc[0]

cnn_comparison_df = cnn_results_df[
    [
        "group",
        "best_epoch",
        "epochs_trained",
        "validation_f1",
        "test_accuracy",
        "test_precision",
        "test_recall",
        "test_f1",
    ]
].copy()

cnn_comparison_df["accuracy_vs_random"] = (
    cnn_comparison_df["test_accuracy"]
    - random_result["test_accuracy"]
)
cnn_comparison_df["f1_vs_random"] = (
    cnn_comparison_df["test_f1"]
    - random_result["test_f1"]
)
cnn_comparison_df["f1_rank"] = (
    cnn_comparison_df["test_f1"]
    .rank(method="min", ascending=False)
    .astype(int)
)
cnn_comparison_df = cnn_comparison_df.sort_values(
    ["f1_rank", "group"]
).reset_index(drop=True)

best_result = cnn_comparison_df.iloc[0]
print(
    f"Best test F1: {best_result['group']} "
    f"({best_result['test_f1']:.4f}, "
    f"change from random "
    f"{best_result['f1_vs_random']:+.4f})"
)

cnn_comparison_df.round(4)

Best test F1: semantic_sentiment_unlabeled (0.8884, change from random +0.0338)

,group,best_epoch,epochs_trained,validation_f1,test_accuracy,test_precision,test_recall,test_f1,accuracy_vs_random,f1_vs_random,f1_rank
0,semantic_sentiment_unlabeled,3,6,0.8877,0.8863,0.8722,0.9053,0.8884,0.0319,0.0338,1
1,semantic_only,4,7,0.8894,0.8849,0.8752,0.8978,0.8863,0.0304,0.0317,2
2,semantic_sentiment,3,6,0.8858,0.8772,0.8618,0.8985,0.8798,0.0228,0.0251,3
3,random,3,6,0.8540,0.8544,0.8534,0.8559,0.8547,0.0000,0.0000,4